# Generated by Django 5.1.1 on 2024-09-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0004_book_create_at2_alter_book_create_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('muallif', models.CharField(max_length=100)),
                ('nashr_sana', models.DateField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('sahifalar_soni', models.IntegerField()),
                ('til', models.CharField(max_length=30)),
                ('janr', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
